### ISSUE TITLE
Mapserver crash

### ISSUE THREAD

**Issue by S-S-X** [minetest-mapserver/mapserver#113]
Related: https://github.com/pandorabox-io/pandorabox.io/issues/502

Mapserver crashes if "bad" data is sent, for example, through in-game LCD.

I dont really have idea and have not debugged anything but I think that crash might happen somewhere under api/mapobjects while it is fetching mapobject data from its datasources and this causes proxy to respond with 502 probably because mapserver is not able to give any meaningful response if it crashes before managing to throw any meaningful errors as response.

**Comment by S-S-X** [comment]
Testing bit more I managed to get error as response through api/mapobjects:
```
sql: Scan error on column index 9, name "key": converting NULL to string is unsupported
```

**Comment by BuckarooBanzay** [comment]
Interesting :astonished: i'll look into it the next few days...
Here the crashlog:

```
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Starting mapserver" version=git-7f7845c51df7eb7f472a9dd6db411e555a220bf8
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/vanessa.txt prefix=colormapping size=1335774 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/advtrains.txt prefix=colormapping size=497 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/scifi_nodes.txt prefix=colormapping size=1315 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/mcl2_colors.txt prefix=colormapping size=59983 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/miles.txt prefix=colormapping size=1289056 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors" filename=/colors/custom.txt prefix=colormapping size=375 useLocal=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loading colors from filesystem" filename=colors.txt
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Loaded custom colors" count=28201
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Migrating database" prefix=mapobjectdb.postgres
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Migration completed" elapsed=8.963584ms prefix=mapobjectdb.postgres
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Starting http server" port=8080 webdev=false
mapserver_1       | time="2020-06-20T18:57:00Z" level=info msg="Starting incremental rendering job" LastMtime=1592678391442
mapserver_1       | time="2020-06-20T18:57:45Z" level=error msg="AddMapData()" mbpos="&{-83 996 13}" obj="&{0xc051a33fa0 -1328 15945 217 digilinelcd 1592679465 map[channel:c text:\n\x1f\xe1\u007f\xc7\xc2]\xba\xd1>\x13^\xe2\xf6u\x06e)\xca+t\x18\x10\"Nc\xa9nyʪ\xd4/\xb1n\xa0\xd4\xc0>m\xbfvO\xb9\x8a\x17\x0edw#*\x0erߔ\x90\xd0u\x17:>e\xad\xe5\x8bs\xf48d\x8f\xb9\xa8I\x1d~c}\xfa\x1cEB\xabmg\xa7,F\xb5Ed9E`\xde\x0faf蟌Ku$\x89\x1b'fm1\\\xe8Бy\x1f\xff\xbbF\xc0u+s\xed\xb7\x18\x80s\xa4\xaek\xdfe\x06\xa5\xf3\xa4\x8a\x14#(\xda\x17\x02G+W[e\xdc\xf2\n\x99\xff'\\\x1b\x95g\xe7\x9a\x18\xfav\f0mM\xbfPn\x9d\xf1\x13,x-jy.iGF\x8dz\x10\x87\xfe\xd2!#E\xb3\x01Ly\xd4H\xd6h\xeb\x01/\x02\xe8N\xfa\x02\x8blJN\xecZ\x97\\*[\x19\xd8\xde\v\x88\r\x10\xd1W\x9d\x88\xf6\x9a$V^\x1e\x8c-:\xfd\x80\xa8\x8a\x0eyî\xba\xccqf\xe5P\xa7\xbb\x04ud\xc0\xfa\x02\xd5=\\8\xfd\x8a\x0e\xb9\x8e:m\xcc+{\xaf\xa8\x19[\xfcY\xbb\x96\xa6\xc5P\\\xf4\xf8\r\xb8\xbb\xe5\x1a4\x9c\x96:1\x1d\x8aµ\xe7\v5s\x8dB\xee\x1f(\x90\\\xd2\x1c\x8bI\xbb\xb7\x0f\xe8L\x89\x1a%E:0\xc5\xf4k\xf4ͮI\x1b\xbfP\xd3\xd0=1\x14k\xe1E\xa1o+4\xef\xe0\x01\x9c\x02?\xe8\x14CR\xca\xea\xb6E\\v\xedr\xea\xbd\xf2\xc2oC\x1c\xef\xa1>\xd4\xf7\xf9\x80\xf5\x88\xab\x1e\xe5T\xaf\xdc(\x1e\xbe;|\f\x0f\v\xc0\x1b\xbbc\xaaL\xb5\x99\xff\xad\xb4\x1eԛ\xc6Q\x80\\\x80y\xbb\xe0\x8f\xbb^\x1f\xbfZb\x11\xf9\xb1i$=\xff\xbc6c\x13\xac\xfb\f \xed\x8deG\xd7\u007f\xeb\xb0\x15\xeeV\xb67\x92\x19\xd5\xfcm\x89\x1b\xf0^\xf7\x8c\x97\xb2C\xaf\xe5\xd3BOQ\x99\x01\xf0֕\xb8\x91\x96\x84\xadg\xfe\xab\xe2Q\x82\xedB\xa6*\xe0epS\x12\x80\x97+\xcdd\xe6{\xa7\xf2\xdc&v*\xa4C]}" prefix=mapobject type="digilines:lcd" x=0 y=9 z=9
mapserver_1       | panic: pq: invalid byte sequence for encoding "UTF8": 0xe1 0x7f 0xc7
mapserver_1       | 
mapserver_1       | goroutine 40 [running]:
mapserver_1       | mapserver/mapobject.(*Listener).OnEvent.func2(0x0, 0x9, 0x9)
mapserver_1       | 	/server/mapobject/listener.go:127 +0x975
mapserver_1       | mapserver/mapblockparser.IterateMapblock(0xc01674c018)
mapserver_1       | 	/server/mapblockparser/iterate.go:7 +0x41
mapserver_1       | mapserver/mapobject.(*Listener).OnEvent(0xc0010dc2c0, 0xafce8f, 0x11, 0xa7bc80, 0xc035094a80)
mapserver_1       | 	/server/mapobject/listener.go:98 +0x388
mapserver_1       | mapserver/eventbus.(*Eventbus).Emit(0xc000294200, 0xafce8f, 0x11, 0xa7bc80, 0xc035094a80)
mapserver_1       | 	/server/eventbus/eventbus.go:35 +0xd1
mapserver_1       | mapserver/mapblockaccessor.(*MapBlockAccessor).GetMapBlock(0xc0002a20c0, 0xc051a33fa0, 0x0, 0x0, 0x0)
mapserver_1       | 	/server/mapblockaccessor/get.go:87 +0x57c
mapserver_1       | mapserver/mapblockrenderer.(*MapBlockRenderer).Render(0xc001260d00, 0xc05c5f12c0, 0xc05c5f12e0, 0x0, 0x0, 0x0)
mapserver_1       | 	/server/mapblockrenderer/renderer.go:157 +0x109f
mapserver_1       | mapserver/tilerenderer.(*TileRenderer).renderImage(0xc0010da040, 0xc05c5f1200, 0x1, 0x0, 0x0, 0x0)
mapserver_1       | 	/server/tilerenderer/renderer.go:142 +0x5b0
mapserver_1       | mapserver/tilerenderer.(*TileRenderer).renderImage(0xc0010da040, 0xc04363d8e0, 0x2, 0x0, 0x0, 0x0)
mapserver_1       | 	/server/tilerenderer/renderer.go:178 +0xc7d
mapserver_1       | mapserver/tilerenderer.(*TileRenderer).Render(...)
mapserver_1       | 	/server/tilerenderer/renderer.go:77
mapserver_1       | mapserver/tilerendererjob.worker(0xc000104990, 0xc00e0ff0e0, 0xc00016cd20)
mapserver_1       | 	/server/tilerendererjob/worker.go:22 +0x388
mapserver_1       | created by mapserver/tilerendererjob.renderMapblocks
mapserver_1       | 	/server/tilerendererjob/common.go:29 +0x102

```

**Comment by BuckarooBanzay** [comment]
i fixed this by disallowing invalid utf8 strings from entering the database.
Don't know how to make sense or clean invalid input... :shrug:
