### ISSUE TITLE
Fails to run in a docker volume

### ISSUE THREAD

**Issue by 56independent** [minetest-mapserver/mapserver#329]
With docker running using a volume at `~/world` for world files:

```
independent@56independent-server ~/world> sudo ./mapserver
INFO[0000] Starting mapserver                            version=4.7.0
INFO[0000] Migrating database                            filename=mapserver.sqlite prefix=mapobjectdb.sqlite
INFO[0000] Migration completed                           elapsed=1.29787ms prefix=mapobjectdb.sqlite
INFO[0000] Created media repository                      bytes=0 count=1637
INFO[0000] Starting http server                          port=8080 webdev=false
INFO[0000] using embed mode                             
INFO[0000] Starting incremental rendering job            LastMtime=1691884299
panic: listen tcp :8080: socket: too many open files

goroutine 1 [running]:
mapserver/web.Serve(0xc000218b40)
	/home/runner/work/mapserver/mapserver/web/serve.go:75 +0xb30
main.main()
	/home/runner/work/mapserver/mapserver/main.go:70 +0x2f5
```

However, when the docker container isn't working, normal output works and i can view the map.

**Comment by 56independent** [comment]
As a side note, i'm not sure if my computers are cursed but it definitely seems to be a possible reason. A lot of people have been wanting to hex me over the last few years, so it does make sense.

**Comment by BuckarooBanzay** [comment]
> panic: listen tcp :8080: socket: too many open files

Uh, this is pretty weird, are you sure nothing else runs on port 8080 (well, it shouldn't, it works with sudo, please check anyway:)

Also: can you run the following command on your shell (as the user you are starting the mapserver with)
```sh
cat /proc/sys/fs/file-nr
```

The minetest server container shouldn't matter anyway, but i might be mistaken...

**Comment by 56independent** [comment]
```
independent@56independent-server ~/world> cat /proc/sys/fs/file-nr
3132	0	9223372036854775807
independent@56independent-server ~/world> sudo cat /proc/sys/fs/file-nr
3164	0	9223372036854775807
```

I'm not exatly sure what these numbers mean.

**Comment by S-S-X** [comment]
> I'm not exactly sure what these numbers mean.

https://www.kernel.org/doc/Documentation/sysctl/fs.txt

Check ulimit configs (/proc is just not-so-simple interface for same stuff but file-nr is just hard allocation limit, not possible soft limit or hard limit for process group).
Docker also has configuration for ulimit conf to limit what container can allocate (basically to prevent one container from depleting all host resources).
Then simple thing: reboot. Same but harder: find out if some process is eating up resources it does not actually use and restart it or fix it other way (depends on sofftware), these you can see under /proc/{pid}.

**Comment by BuckarooBanzay** [comment]
no new infos, closing this, if this still happens feel free to reopen
