### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by acmgit** [minetest-mapserver/mapserver#364]
From Server Zeitsprung:

Crashreport:

```
Jan 25 06:30:18 zeitsprung mapserver[161780]: goroutine 52 [running]:
Jan 25 06:30:18 zeitsprung mapserver[161780]: mapserver/tilerendererjob.incrementalRender(0xc0004b2750)
Jan 25 06:30:18 zeitsprung mapserver[161780]:         /home/runner/work/mapserver/mapserver/tilerendererjob/incremental.go:30 +0x54b
Jan 25 06:30:18 zeitsprung mapserver[161780]: mapserver/tilerendererjob.Job(0xc0004b2750)
Jan 25 06:30:18 zeitsprung mapserver[161780]:         /home/runner/work/mapserver/mapserver/tilerendererjob/job.go:27 +0x4f
Jan 25 06:30:18 zeitsprung mapserver[161780]: created by main.main in goroutine 1
Jan 25 06:30:18 zeitsprung mapserver[161780]:         /home/runner/work/mapserver/mapserver/main.go:77 +0x37a
Jan 25 06:30:18 zeitsprung systemd[1]: minetest_mapserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 25 06:30:18 zeitsprung systemd[1]: minetest_mapserver.service: Failed with result 'exit-code'.
Jan 25 06:30:18 zeitsprung systemd[1]: minetest_mapserver.service: Consumed 46min 55.603s CPU time.
```

mapserver.json:

```
{
	"configversion": 1,
	"port": 8081,
	"enableprometheus": true,
	"enablerendering": true,
	"enablesearch": true,
	"enableinitialrendering": true,
	"enabletransparency": true,
	"enablemediarepository": false,
	"webdev": false,
	"webapi": {
		"enablemapblock": false,
		"secretkey": "xxxxxx"
	},
	"layers": [
		{
			"id": 0,
			"name": "Ground",
			"from": -10,
			"to": 100
		}
	],
	"renderingfetchlimit": 500,
	"renderingjobs": 6,
	"renderingqueue": 10,
	"incrementalrenderingtimer": "5s",
	"mapobjects": {
		"areas": true,
		"bones": true,
		"protector": false,
		"xpprotector": true,
		"privprotector": false,
		"technic_quarry": false,
		"technic_switch": false,
		"technic_anchor": false,
		"technic_reactor": false,
		"luacontroller": false,
		"digiterms": false,
		"digilines": false,
		"travelnet": true,
		"mapserver_player": true,
		"mapserver_poi": true,
		"mapserver_label": true,
		"mapserver_trainline": false,
		"mapserver_border": true,
		"tileserverlegacy": true,
		"mission": false,
		"jumpdrive": false,
		"smartshop": true,
		"fancyvend": false,
		"atm": false,
		"train": false,
		"trainsignal": false,
		"minecart": true,
		"locator": false,
		"signs": true,
		"mapserver_airutils": false
	},
	"mapblockaccessor": {
		"expiretime": "10s",
		"purgetime": "15s",
		"maxitems": 50
	},
	"defaultoverlays": [
		"mapserver_poi",
		"mapserver_label",
		"mapserver_player"
	],
	"skins": {
		"enableskinsdb": true,
		"skinspath": "/usr/share/minetest/games/Smalltech_Game/mods/skinsdb/textures"
	},
	"worldpath": "./",
	"datapath": "./",
	"ColorsTxtPath": "./"
```

After a restart, it works again.

**Comment by BuckarooBanzay** [comment]
uh, why did that pop up in my notification feed again? wasn't there a comment about being the wrong service or something here before? :confused:

**Comment by BuckarooBanzay** [comment]
the panic is from here:
https://github.com/minetest-mapserver/mapserver/blob/e667ca580af2d2dfe4322df18c9b3ac06614fa0e/tilerendererjob/incremental.go#L27-L31

looks like a database issue, is that still a problem? if so: what db are you using?

**Comment by acmgit** [comment]
As long it works after a restart, so i can configure it to restart it.
The world itself works with postgresql.

**Comment by BuckarooBanzay** [comment]
> As long it works after a restart, so i can configure it to restart it.

Oh, could it be that the database is not ready yet (i didn't see any cause in the logs, maybe there is more?).

**Comment by acmgit** [comment]
The program itself don't log anything, so this is all what i have.
It running fine and then suddenly it crashes. Strange is, restart it, and it works again.
What can be wrong with the Database? 
Space is enough and the game is running fine.
